import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  runApp(const GGOfflineApp());
}

class GGOfflineApp extends StatelessWidget {
  const GGOfflineApp({super.key});
  @override
  Widget build(BuildContext context) => MaterialApp(
    title: 'GG Messenger', debugShowCheckedModeBanner: false,
    theme: ThemeData(useMaterial3: true, colorScheme: ColorScheme.fromSeed(seedColor: const Color(0xFF7C4DFF))),
    darkTheme: ThemeData(useMaterial3: true, brightness: Brightness.dark, colorScheme: ColorScheme.fromSeed(seedColor: const Color(0xFF7C4DFF), brightness: Brightness.dark), scaffoldBackgroundColor: const Color(0xFF08070C)),
    themeMode: ThemeMode.system, home: const OfflineGate(),
  );
}

class OfflineStore {
  static const profileKey = 'gg_offline_profile_v1';
  static const chatsKey = 'gg_offline_chats_v1';
  Future<SharedPreferences> get prefs => SharedPreferences.getInstance();
  Future<Map<String, dynamic>?> profile() async { final raw = (await prefs).getString(profileKey); if (raw == null) return null; try { return Map<String, dynamic>.from(jsonDecode(raw) as Map); } catch (_) { return null; } }
  Future<void> saveProfile(String name, String username) async => (await prefs).setString(profileKey, jsonEncode({'name': name, 'username': username}));
  Future<void> logout() async => (await prefs).remove(profileKey);
  Future<List<Map<String, dynamic>>> chats() async { final raw = (await prefs).getString(chatsKey); if (raw == null) return []; try { return (jsonDecode(raw) as List).map((e) => Map<String, dynamic>.from(e as Map)).toList(); } catch (_) { return []; } }
  Future<void> saveChats(List<Map<String, dynamic>> value) async => (await prefs).setString(chatsKey, jsonEncode(value));
  Future<void> clearChats() async => (await prefs).remove(chatsKey);
}

class OfflineGate extends StatefulWidget { const OfflineGate({super.key}); @override State<OfflineGate> createState() => _OfflineGateState(); }
class _OfflineGateState extends State<OfflineGate> {
  final store = OfflineStore(); Map<String, dynamic>? profile; bool loading = true;
  @override void initState() { super.initState(); _load(); }
  Future<void> _load() async { final p = await store.profile(); if (mounted) setState(() { profile = p; loading = false; }); }
  Future<void> _enter(String name, String username) async { await store.saveProfile(name, username); if (mounted) setState(() => profile = {'name': name, 'username': username}); }
  @override Widget build(BuildContext context) { if (loading) return const Scaffold(body: Center(child: CircularProgressIndicator())); return profile == null ? OfflineWelcome(onContinue: _enter) : OfflineHome(profile: profile!, store: store, onLogout: () async { await store.logout(); if (mounted) setState(() => profile = null); }); }
}

class OfflineWelcome extends StatefulWidget { const OfflineWelcome({super.key, required this.onContinue}); final Future<void> Function(String, String) onContinue; @override State<OfflineWelcome> createState() => _OfflineWelcomeState(); }
class _OfflineWelcomeState extends State<OfflineWelcome> {
  final name = TextEditingController(), username = TextEditingController(); bool saving = false;
  @override void dispose() { name.dispose(); username.dispose(); super.dispose(); }
  Future<void> _continue() async { final n = name.text.trim(); var u = username.text.trim().replaceAll(RegExp(r'[^a-zA-Z0-9_]'), ''); if (n.isEmpty) { ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Enter your name.'))); return; } if (u.isEmpty) u = n.toLowerCase().replaceAll(RegExp(r'[^a-z0-9]'), ''); setState(() => saving = true); await widget.onContinue(n, u); }
  @override Widget build(BuildContext context) => Scaffold(body: SafeArea(child: Center(child: SingleChildScrollView(padding: const EdgeInsets.all(28), child: ConstrainedBox(constraints: const BoxConstraints(maxWidth: 520), child: Column(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Container(padding: const EdgeInsets.all(24), decoration: BoxDecoration(borderRadius: BorderRadius.circular(30), color: Theme.of(context).colorScheme.primaryContainer), child: const Icon(Icons.wifi_off_rounded, size: 64)), const SizedBox(height: 28), const Text('GG Messenger', style: TextStyle(fontSize: 30, fontWeight: FontWeight.w900)), const SizedBox(height: 8), const Text('Offline mode', style: TextStyle(fontSize: 18, fontWeight: FontWeight.w700)), const SizedBox(height: 8), const Text('Your profile and conversations are stored on this device. No website, Supabase, or server connection is used.'), const SizedBox(height: 26), TextField(controller: name, textInputAction: TextInputAction.next, decoration: const InputDecoration(labelText: 'Your name', prefixIcon: Icon(Icons.person_outline_rounded))), const SizedBox(height: 14), TextField(controller: username, decoration: const InputDecoration(labelText: 'Username', prefixIcon: Icon(Icons.alternate_email_rounded))), const SizedBox(height: 22), FilledButton.icon(onPressed: saving ? null : _continue, icon: const Icon(Icons.arrow_forward_rounded), label: Text(saving ? 'Saving…' : 'Enter GG')), const SizedBox(height: 16), const Center(child: Text('Works without internet', style: TextStyle(fontWeight: FontWeight.w700))) ]))))));
}

class OfflineHome extends StatefulWidget { const OfflineHome({super.key, required this.profile, required this.store, required this.onLogout}); final Map<String, dynamic> profile; final OfflineStore store; final Future<void> Function() onLogout; @override State<OfflineHome> createState() => _OfflineHomeState(); }
class _OfflineHomeState extends State<OfflineHome> {
  int tab = 0; List<Map<String, dynamic>> chats = []; bool loading = true;
  @override void initState() { super.initState(); _loadChats(); }
  Future<void> _loadChats() async { final c = await widget.store.chats(); if (mounted) setState(() { chats = c; loading = false; }); }
  Future<void> _newChat() async { final c = TextEditingController(); final title = await showDialog<String>(context: context, builder: (context) => AlertDialog(title: const Text('New offline chat'), content: TextField(controller: c, autofocus: true, decoration: const InputDecoration(labelText: 'Chat name')), actions: [TextButton(onPressed: () => Navigator.pop(context), child: const Text('Cancel')), FilledButton(onPressed: () => Navigator.pop(context, c.text.trim()), child: const Text('Create'))])); c.dispose(); if (title == null || title.isEmpty) return; final chat = <String, dynamic>{'id': DateTime.now().microsecondsSinceEpoch.toString(), 'title': title, 'messages': <Map<String, dynamic>>[]}; final updated = [...chats, chat]; await widget.store.saveChats(updated); if (mounted) { setState(() => chats = updated); await _openChat(chat); } }
  Future<void> _openChat(Map<String, dynamic> chat) async { final updated = await Navigator.push<List<Map<String, dynamic>>>(context, MaterialPageRoute(builder: (_) => OfflineChatPage(title: chat['title']?.toString() ?? 'Chat', messages: List<Map<String, dynamic>>.from((chat['messages'] as List?) ?? [])))); if (updated == null) return; final copy = chats.map((item) => item['id'] == chat['id'] ? {...item, 'messages': updated} : item).toList(); await widget.store.saveChats(copy); if (mounted) setState(() => chats = copy); }
  Future<void> _clearChats() async { await widget.store.clearChats(); if (mounted) setState(() => chats = []); }
  @override Widget build(BuildContext context) { final pages = [_ChatsTab(chats: chats, loading: loading, onOpen: _openChat, onNew: _newChat), const _UpdatesTab(), const _CallsTab()]; final titles = ['Chats', 'Updates', 'Calls']; final name = widget.profile['name']?.toString() ?? 'GG User'; final username = widget.profile['username']?.toString() ?? ''; return Scaffold(appBar: AppBar(title: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text(titles[tab]), Text('@$username · Offline', style: Theme.of(context).textTheme.labelSmall?.copyWith(fontWeight: FontWeight.w700))]), actions: [PopupMenuButton<String>(onSelected: (v) async { if (v == 'clear') await _clearChats(); if (v == 'logout') await widget.onLogout(); }, itemBuilder: (_) => const [PopupMenuItem(value: 'clear', child: Text('Clear local chats')), PopupMenuItem(value: 'logout', child: Text('Log out'))]), Padding(padding: const EdgeInsets.only(right: 12), child: CircleAvatar(child: Text(name.isEmpty ? 'G' : name[0].toUpperCase())))], body: IndexedStack(index: tab, children: pages), floatingActionButton: tab == 0 ? FloatingActionButton.extended(onPressed: _newChat, icon: const Icon(Icons.edit_rounded), label: const Text('New chat')) : null, bottomNavigationBar: NavigationBar(selectedIndex: tab, onDestinationSelected: (v) => setState(() => tab = v), destinations: const [NavigationDestination(icon: Icon(Icons.chat_bubble_outline_rounded), selectedIcon: Icon(Icons.chat_bubble_rounded), label: 'Chats'), NavigationDestination(icon: Icon(Icons.circle_outlined), selectedIcon: Icon(Icons.circle, size: 20), label: 'Updates'), NavigationDestination(icon: Icon(Icons.call_outlined), selectedIcon: Icon(Icons.call_rounded), label: 'Calls')])); }
}

class _ChatsTab extends StatelessWidget { const _ChatsTab({required this.chats, required this.loading, required this.onOpen, required this.onNew}); final List<Map<String, dynamic>> chats; final bool loading; final Future<void> Function(Map<String, dynamic>) onOpen; final Future<void> Function() onNew; @override Widget build(BuildContext context) { if (loading) return const Center(child: CircularProgressIndicator()); if (chats.isEmpty) return Center(child: Padding(padding: const EdgeInsets.all(28), child: Column(mainAxisSize: MainAxisSize.min, children: [const Icon(Icons.cloud_off_rounded, size: 64), const SizedBox(height: 14), const Text('No local chats yet', style: TextStyle(fontSize: 20, fontWeight: FontWeight.w900)), const SizedBox(height: 8), const Text('Create a conversation. It stays on this device.', textAlign: TextAlign.center), const SizedBox(height: 18), FilledButton.icon(onPressed: onNew, icon: const Icon(Icons.add_rounded), label: const Text('Create chat'))]))); return ListView.separated(padding: const EdgeInsets.fromLTRB(12, 8, 12, 120), itemCount: chats.length, separatorBuilder: (_, __) => const SizedBox(height: 6), itemBuilder: (_, i) { final chat = chats[i]; final messages = List<Map<String, dynamic>>.from((chat['messages'] as List?) ?? []); final last = messages.isEmpty ? 'Offline conversation' : messages.last['text']?.toString() ?? ''; return ListTile(shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(20)), tileColor: Theme.of(context).colorScheme.surfaceContainerHighest, leading: CircleAvatar(child: Text((chat['title']?.toString() ?? 'G')[0].toUpperCase())), title: Text(chat['title']?.toString() ?? 'Chat', style: const TextStyle(fontWeight: FontWeight.w800)), subtitle: Text(last, maxLines: 1, overflow: TextOverflow.ellipsis), trailing: const Icon(Icons.chevron_right_rounded), onTap: () => onOpen(chat)); }); } }

class OfflineChatPage extends StatefulWidget { const OfflineChatPage({super.key, required this.title, required this.messages}); final String title; final List<Map<String, dynamic>> messages; @override State<OfflineChatPage> createState() => _OfflineChatPageState(); }
class _OfflineChatPageState extends State<OfflineChatPage> {
  late List<Map<String, dynamic>> messages; final controller = TextEditingController(); final scroll = ScrollController();
  @override void initState() { super.initState(); messages = [...widget.messages]; }
  @override void dispose() { controller.dispose(); scroll.dispose(); super.dispose(); }
  Future<void> _send() async { final text = controller.text.trim(); if (text.isEmpty) return; controller.clear(); setState(() => messages.add({'from': 'me', 'text': text, 'time': DateTime.now().toIso8601String()})); await Future<void>.delayed(const Duration(milliseconds: 180)); if (!mounted) return; setState(() => messages.add({'from': 'gg', 'text': _reply(text), 'time': DateTime.now().toIso8601String()})); if (scroll.hasClients) scroll.animateTo(scroll.position.maxScrollExtent, duration: const Duration(milliseconds: 180), curve: Curves.easeOut); }
  String _reply(String input) { final t = input.toLowerCase(); if (t.contains('hello') || t.contains('hi')) return 'Hello! 👋 I am GG. You are using offline mode.'; if (t.contains('help')) return 'I can keep this conversation locally while you are offline. Online messaging and internet AI are disabled.'; if (t.contains('time')) return 'Your device time is ${TimeOfDay.now().format(context)}.'; return 'Saved locally. Offline GG cannot contact the internet, but your message is safely stored on this device.'; }
  @override Widget build(BuildContext context) => Scaffold(appBar: AppBar(title: Text(widget.title), actions: const [Padding(padding: EdgeInsets.only(right: 14), child: Icon(Icons.wifi_off_rounded))]), body: Column(children: [Expanded(child: messages.isEmpty ? const Center(child: Text('Start your offline conversation')) : ListView.builder(controller: scroll, padding: const EdgeInsets.all(16), itemCount: messages.length, itemBuilder: (_, i) { final m = messages[i]; final mine = m['from'] == 'me'; return Align(alignment: mine ? Alignment.centerRight : Alignment.centerLeft, child: Container(constraints: const BoxConstraints(maxWidth: 330), margin: const EdgeInsets.only(bottom: 10), padding: const EdgeInsets.symmetric(horizontal: 15, vertical: 11), decoration: BoxDecoration(color: mine ? Theme.of(context).colorScheme.primaryContainer : Theme.of(context).colorScheme.surfaceContainerHighest, borderRadius: BorderRadius.circular(18)), child: Text(m['text']?.toString() ?? ''))); })), SafeArea(top: false, child: Padding(padding: const EdgeInsets.fromLTRB(12, 8, 12, 12), child: Row(children: [Expanded(child: TextField(controller: controller, onSubmitted: (_) => _send(), textInputAction: TextInputAction.send, decoration: const InputDecoration(hintText: 'Message offline…'))), const SizedBox(width: 8), IconButton.filled(onPressed: _send, icon: const Icon(Icons.send_rounded))]))) ]));
}
class _UpdatesTab extends StatelessWidget { const _UpdatesTab(); @override Widget build(BuildContext context) => const Center(child: Padding(padding: EdgeInsets.all(28), child: Column(mainAxisSize: MainAxisSize.min, children: [Icon(Icons.update_rounded, size: 64), SizedBox(height: 12), Text('Offline Updates', style: TextStyle(fontSize: 20, fontWeight: FontWeight.w900)), SizedBox(height: 8), Text('Online status sharing is disabled in this offline build.', textAlign: TextAlign.center)]))); }
class _CallsTab extends StatelessWidget { const _CallsTab(); @override Widget build(BuildContext context) => const Center(child: Padding(padding: EdgeInsets.all(28), child: Column(mainAxisSize: MainAxisSize.min, children: [Icon(Icons.phone_disabled_rounded, size: 64), SizedBox(height: 12), Text('Calls are offline', style: TextStyle(fontSize: 20, fontWeight: FontWeight.w900)), SizedBox(height: 8), Text('Internet calling is disabled because this version has no server connection.', textAlign: TextAlign.center)]))); }
