from pathlib import Path

p = Path('lib/chat_page.dart')
s = p.read_text()
old = "Expanded(child: Container(padding: const EdgeInsets.symmetric(horizontal: 5), decoration: BoxDecoration(color: scheme.surfaceContainerHighest, borderRadius: BorderRadius.circular(25), border: Border.all(color: scheme.outlineVariant.withValues(alpha: .45))), child: Row(crossAxisAlignment: CrossAxisAlignment.end, children: [Expanded(child: TextField(controller: controller, focusNode: focus, minLines: 1, maxLines: 5, textCapitalization: TextCapitalization.sentences, onChanged: (value) => typingService.setTyping(value.trim().isNotEmpty), decoration: InputDecoration(hintText: editingId == null ? 'Message' : 'Edit message', border: InputBorder.none, contentPadding: const EdgeInsets.symmetric(horizontal: 13, vertical: 11), suffixIcon: IconButton(tooltip: 'Emoji', onPressed: () => setState(() => showEmoji = !showEmoji), icon: const Icon(Icons.emoji_emotions_outlined)))))])),"
new = "Expanded(\n                child: Container(\n                  padding: const EdgeInsets.symmetric(horizontal: 5),\n                  decoration: BoxDecoration(\n                    color: scheme.surfaceContainerHighest,\n                    borderRadius: BorderRadius.circular(25),\n                    border: Border.all(color: scheme.outlineVariant.withValues(alpha: .45)),\n                  ),\n                  child: Row(\n                    crossAxisAlignment: CrossAxisAlignment.end,\n                    children: [\n                      Expanded(\n                        child: TextField(\n                          controller: controller,\n                          focusNode: focus,\n                          minLines: 1,\n                          maxLines: 5,\n                          textCapitalization: TextCapitalization.sentences,\n                          onChanged: (value) => typingService.setTyping(value.trim().isNotEmpty),\n                          decoration: InputDecoration(\n                            hintText: editingId == null ? 'Message' : 'Edit message',\n                            border: InputBorder.none,\n                            contentPadding: const EdgeInsets.symmetric(horizontal: 13, vertical: 11),\n                            suffixIcon: IconButton(\n                              tooltip: 'Emoji',\n                              onPressed: () => setState(() => showEmoji = !showEmoji),\n                              icon: const Icon(Icons.emoji_emotions_outlined),\n                            ),\n                          ),\n                        ),\n                      ),\n                    ],\n                  ),\n                ),\n              ),"
if old not in s:
    raise SystemExit('Malformed chat composer block not found')
p.write_text(s.replace(old, new, 1))
print('Fixed chat composer Dart syntax.')
